import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import API from '../services/api';
import toast from 'react-hot-toast';
import { 
  FiClock, FiPlus, FiSunrise, FiSun, FiSunset, FiMoon, 
  FiCpu, FiCalendar, FiRefreshCw, FiUsers, FiCopy 
} from 'react-icons/fi';
import { motion, AnimatePresence } from 'framer-motion';

const getShiftDetails = (shift) => {
  const styles = {
    morning: { bg: 'bg-amber-50 dark:bg-amber-900/20', border: 'border-amber-200 dark:border-amber-800', text: 'text-amber-700 dark:text-amber-300', Icon: FiSunrise, col: 'text-amber-500', time: '6:00 AM - 12:00 PM' },
    afternoon: { bg: 'bg-orange-50 dark:bg-orange-900/20', border: 'border-orange-200 dark:border-orange-800', text: 'text-orange-700 dark:text-orange-300', Icon: FiSun, col: 'text-orange-500', time: '12:00 PM - 6:00 PM' },
    evening: { bg: 'bg-blue-50 dark:bg-blue-900/20', border: 'border-blue-200 dark:border-blue-800', text: 'text-blue-700 dark:text-blue-300', Icon: FiSunset, col: 'text-blue-500', time: '6:00 PM - 10:00 PM' },
    night: { bg: 'bg-indigo-50 dark:bg-indigo-900/20', border: 'border-indigo-200 dark:border-indigo-800', text: 'text-indigo-700 dark:text-indigo-300', Icon: FiMoon, col: 'text-indigo-500', time: '10:00 PM - 6:00 AM' }
  };
  return styles[shift?.toLowerCase()] || styles.morning;
};

export default function Schedule() {
  const { currentCircle } = useAuth();
  const [schedule, setSchedule] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [activeDay, setActiveDay] = useState(0);

  useEffect(() => {
    if (currentCircle?._id) loadSchedule();
    else setLoading(false);
  }, [currentCircle]);

  const loadSchedule = async () => {
    try {
      const { data } = await API.get(`/schedule/circle/${currentCircle._id}`);
      setSchedule(data.data);
    } catch (error) {
      console.error("Schedule load error", error);
    } finally {
      setLoading(false);
    }
  };

  // 🤖 AI GENERATE LOGIC
  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const today = new Date().toISOString().split('T')[0];
      const { data } = await API.post('/schedule/generate', {
        circleId: currentCircle._id,
        weekStart: today
      });
      setSchedule(data.data);
      toast.success('Smart schedule generated by AI!');
    } catch (error) {
      toast.error('AI generation failed. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return (
    <div className="p-12 text-center text-slate-400 font-bold animate-pulse uppercase tracking-widest">
      Syncing Care Schedule...
    </div>
  );

  return (
    <div className="relative min-h-full w-full bg-slate-50 dark:bg-slate-900 overflow-hidden p-1">
      {/* Background Orbs */}
      <div className="absolute -top-24 -left-24 w-96 h-96 bg-indigo-400/10 rounded-full filter blur-[100px] animate-pulse"></div>
      <div className="absolute -bottom-24 -right-24 w-96 h-96 bg-blue-400/10 rounded-full filter blur-[100px] animate-pulse delay-700"></div>

      <div className="relative z-10 space-y-8 max-w-4xl mx-auto">
        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white tracking-tight uppercase">Care Schedule</h1>
            <p className="text-sm font-medium text-slate-500 uppercase tracking-widest">Shift Management</p>
          </div>
          
          {/* 🤖 AI Generate / Regenerate Button */}
          <motion.button 
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleGenerate}
            disabled={generating}
            className="flex items-center justify-center gap-2 bg-gradient-to-r from-indigo-600 to-blue-600 text-white px-6 py-3 rounded-2xl font-black shadow-lg shadow-indigo-600/30 uppercase tracking-tighter disabled:opacity-50"
          >
            {generating ? (
              <FiRefreshCw className="animate-spin" size={20} />
            ) : (
              <FiCpu size={20} />
            )}
            {generating ? 'AI Processing...' : (schedule ? 'Regenerate with AI' : 'Generate AI Schedule')}
          </motion.button>
        </header>

        {!schedule || !schedule.schedule || schedule.schedule.length === 0 ? (
          /* NO SCHEDULE VIEW */
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="p-16 bg-white/60 dark:bg-slate-800/40 backdrop-blur-2xl rounded-[3rem] border border-white/20 shadow-xl text-center">
            <div className="w-20 h-20 bg-slate-100 dark:bg-slate-700 rounded-3xl flex items-center justify-center mx-auto mb-6">
              <FiCalendar size={40} className="text-slate-400" />
            </div>
            <h3 className="text-2xl font-bold text-slate-900 dark:text-white uppercase tracking-tight">No Active Schedule</h3>
            <p className="text-slate-500 dark:text-slate-400 mt-2 mb-8 max-w-xs mx-auto text-sm">
              Use our AI to automatically distribute caregiver shifts among your circle members.
            </p>
            <button 
              onClick={handleGenerate}
              className="px-8 py-4 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-2xl font-bold uppercase tracking-widest text-xs hover:scale-105 transition-all shadow-xl"
            >
              Start AI Generation
            </button>
          </motion.div>
        ) : (
          /* ACTIVE SCHEDULE VIEW */
          <div className="space-y-8">
            {/* Day Tabs */}
            <div className="flex gap-2 overflow-x-auto pb-2 custom-scrollbar">
              {schedule.schedule.map((day, i) => (
                <button 
                  key={i} 
                  onClick={() => setActiveDay(i)} 
                  className={`flex-shrink-0 px-6 py-3 rounded-2xl text-xs font-black uppercase transition-all ${
                    activeDay === i 
                    ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/30 ring-2 ring-indigo-500/20' 
                    : 'bg-white dark:bg-slate-800 text-slate-500 border border-slate-100 dark:border-slate-700'
                  }`}
                >
                  {day.dayName?.slice(0, 3)}
                </button>
              ))}
            </div>

            {/* Shifts List */}
            <div className="space-y-4">
              <AnimatePresence mode="wait">
                <motion.div 
                  key={activeDay}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-4"
                >
                  {schedule.schedule[activeDay]?.shifts?.map((shift, j) => {
                    const details = getShiftDetails(shift.shift);
                    return (
                      <div key={j} className={`p-6 rounded-[2rem] border ${details.border} ${details.bg} backdrop-blur-md shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4`}>
                        <div className="flex items-center gap-4">
                          <div className="p-4 bg-white/50 dark:bg-slate-800/50 rounded-2xl text-2xl shadow-sm">
                            <details.Icon className={details.col} />
                          </div>
                          <div>
                            <h3 className={`font-black text-lg ${details.text} uppercase tracking-tight`}>{shift.shift} Shift</h3>
                            <p className="text-xs font-bold opacity-60 flex items-center gap-1.5 uppercase">
                              <FiClock size={12}/> {details.time}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-3 bg-white/30 dark:bg-black/10 px-4 py-2 rounded-2xl">
                          <div className="w-8 h-8 bg-indigo-600 rounded-full flex items-center justify-center text-white font-bold text-xs">
                            {shift.assignedTo?.name?.charAt(0) || '?'}
                          </div>
                          <div>
                            <p className={`font-black text-xs ${details.text} uppercase tracking-widest`}>
                              {shift.assignedTo?.name || 'Unassigned'}
                            </p>
                            <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">
                              {shift.autoAssigned ? 'AI Assigned' : 'Manual'}
                            </p>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}